### ISSUE TITLE
You should ask to add the vars to the event instead of using globals^^

### ISSUE THREAD

**Issue by Nicofuma** [phpBBSEO/meta#2]
Instead of using globals (here and a few lines below https://github.com/phpBBSEO/meta/blob/master/event/listener.php#L67) you should create a ticket in the tracker (and then send a PR) to add these vars to the event. :)

**Comment by dcz** [comment]
Unfortunately, there is a lot more places where the global hax is required, especially in the USU. So you're right, we need to start posting requests, but since it will be a rather long process, we first need to release working exts.
For meta, there is even a more blocking issue : https://area51.phpbb.com/phpBB/viewtopic.php?f=81&t=45907
still unfixed.
